//! C ABI boundary for RadishLex host smoke tests.

mod abi;
mod apple_p256_product;
mod apple_secure_enclave_key_agreement_product;
mod apple_secure_enclave_product;
mod buffer;
mod contract;
mod demo_engine;
mod dictionary;
mod engine;
mod error;
mod ffi_support;
mod key;
mod key_result;
mod learning_status;
mod manager_sync_product_status;
mod personalization;
mod rank_explain;
mod rime_runtime;
mod session;
mod snapshot;
mod sync_status;

pub use abi::*;
pub use apple_p256_product::{
    RadishLexAppleP256ProductSmokeSummary, RadishLexAppleP256ProductStatus,
    RADISHLEX_APPLE_P256_ERROR_ACCESS_DENIED, RADISHLEX_APPLE_P256_ERROR_BACKEND_UNAVAILABLE,
    RADISHLEX_APPLE_P256_ERROR_CORRUPTED, RADISHLEX_APPLE_P256_ERROR_DETAIL_ACCESS_UNSPECIFIED,
    RADISHLEX_APPLE_P256_ERROR_DETAIL_AUTHENTICATION_FAILED,
    RADISHLEX_APPLE_P256_ERROR_DETAIL_MISSING_ENTITLEMENT, RADISHLEX_APPLE_P256_ERROR_DETAIL_NONE,
    RADISHLEX_APPLE_P256_ERROR_DETAIL_READ_ONLY, RADISHLEX_APPLE_P256_ERROR_DETAIL_RESTRICTED_API,
    RADISHLEX_APPLE_P256_ERROR_DETAIL_UNCLASSIFIED_PLATFORM_STATUS,
    RADISHLEX_APPLE_P256_ERROR_DETAIL_WRITE_PERMISSION, RADISHLEX_APPLE_P256_ERROR_LOCKED,
    RADISHLEX_APPLE_P256_ERROR_MISSING, RADISHLEX_APPLE_P256_ERROR_NONE,
    RADISHLEX_APPLE_P256_ERROR_OTHER, RADISHLEX_APPLE_P256_ERROR_REVOKED,
    RADISHLEX_APPLE_P256_ERROR_UNSUPPORTED, RADISHLEX_APPLE_P256_ERROR_USER_PRESENCE_REQUIRED,
    RADISHLEX_APPLE_P256_PRODUCT_SMOKE_VERSION, RADISHLEX_APPLE_P256_PRODUCT_STATUS_VERSION,
    RADISHLEX_APPLE_P256_SCENARIO_CLEANUP_LOCKED_SIGN,
    RADISHLEX_APPLE_P256_SCENARIO_EXPECT_DENIED_CREATE,
    RADISHLEX_APPLE_P256_SCENARIO_EXPECT_LOCKED_SIGN, RADISHLEX_APPLE_P256_SCENARIO_LIFECYCLE,
    RADISHLEX_APPLE_P256_SCENARIO_PREPARE_LOCKED_SIGN,
    RADISHLEX_APPLE_P256_SMOKE_CAPABILITY_MISMATCH, RADISHLEX_APPLE_P256_SMOKE_CREATE_FAILED,
    RADISHLEX_APPLE_P256_SMOKE_DELETE_FAILED,
    RADISHLEX_APPLE_P256_SMOKE_EXPECTED_FAILURE_NOT_OBSERVED,
    RADISHLEX_APPLE_P256_SMOKE_GATE_DISABLED, RADISHLEX_APPLE_P256_SMOKE_GO_VERIFY_FAILED,
    RADISHLEX_APPLE_P256_SMOKE_INTERNAL_ERROR, RADISHLEX_APPLE_P256_SMOKE_INVALID_ARGUMENT,
    RADISHLEX_APPLE_P256_SMOKE_MISSING_CHECK_FAILED, RADISHLEX_APPLE_P256_SMOKE_PASSED,
    RADISHLEX_APPLE_P256_SMOKE_RELOAD_FAILED, RADISHLEX_APPLE_P256_SMOKE_RUST_VERIFY_FAILED,
    RADISHLEX_APPLE_P256_SMOKE_UNEXPECTED_ERROR_CATEGORY,
    RADISHLEX_APPLE_P256_SMOKE_UNSUPPORTED_BUILD,
};
pub use apple_secure_enclave_key_agreement_product::*;
pub use apple_secure_enclave_product::{
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_PRODUCT_SMOKE_VERSION,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_PRODUCT_STATUS_VERSION,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_CLEANUP_LOCKED_SIGN,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_EXPECT_DENIED_CREATE,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_EXPECT_LOCKED_SIGN,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_EXPECT_UNSUPPORTED_CREATE,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_LIFECYCLE,
    RADISHLEX_APPLE_SECURE_ENCLAVE_P256_SCENARIO_PREPARE_LOCKED_SIGN,
};
pub use buffer::RadishLexBuffer;
pub use contract::{
    RadishLexFfiContract, RADISHLEX_ABI_CONTRACT_VERSION,
    RADISHLEX_FFI_PANIC_BOUNDARY_CATCH_UNWIND, RADISHLEX_SESSION_THREAD_POLICY_OWNER_THREAD,
};
pub use dictionary::{
    RadishLexDeletedTermList, RadishLexDeletedTermView, RadishLexDictionaryExportSummary,
    RadishLexDictionaryImportSummary, RadishLexDictionaryInspectSummary, RadishLexImportBatchList,
    RadishLexImportBatchView, RadishLexUserTermList, RadishLexUserTermView,
    RADISHLEX_DICTIONARY_FORMAT_USER_TERMS_V1, RADISHLEX_SYNC_CLASS_P2_ENCRYPTED_SYNC,
    RADISHLEX_TERM_SOURCE_ENGINE_SELECTION, RADISHLEX_TERM_SOURCE_MANUAL_ADD,
    RADISHLEX_TERM_SOURCE_MANUAL_IMPORT, RADISHLEX_TERM_SOURCE_PHRASE_LEARNING,
    RADISHLEX_TERM_STATUS_ACTIVE, RADISHLEX_TERM_STATUS_DELETED, RADISHLEX_TERM_STATUS_SUPPRESSED,
};
pub use engine::{
    RadishLexPersonalizedRimeSessionOptions, RadishLexRimeSessionOptions, RadishLexSessionOptions,
    RADISHLEX_ENGINE_KIND_DEMO, RADISHLEX_ENGINE_KIND_RIME,
    RADISHLEX_PERSONALIZED_RIME_SESSION_OPTIONS_VERSION, RADISHLEX_RIME_SESSION_OPTIONS_VERSION,
    RADISHLEX_SESSION_OPTIONS_VERSION,
};
pub use error::{RadishLexError, RadishLexStatusCode};
pub use key::*;
pub use key_result::*;
pub use learning_status::RadishLexLearningStatusSummary;
pub use manager_sync_product_status::*;
pub use personalization::*;
pub use rank_explain::{RadishLexRankExplain, RadishLexRankExplainView};
pub use rime_runtime::radishlex_rime_runtime_shutdown;
pub use session::RadishLexSession;
pub use snapshot::{
    RadishLexCandidateView, RadishLexSnapshot, RadishLexStringView,
    RADISHLEX_CANDIDATE_SOURCE_ENGINE, RADISHLEX_CANDIDATE_SOURCE_PERSONALIZED,
    RADISHLEX_CANDIDATE_SOURCE_SYSTEM, RADISHLEX_CANDIDATE_SOURCE_USER_DICTIONARY,
};
pub use sync_status::RadishLexSyncPreflightSummary;
