#ifndef RADISHLEX_INSTALLER_BRIDGE_H
#define RADISHLEX_INSTALLER_BRIDGE_H

#include <stdint.h>

#define RADISHLEX_INSTALLER_BRIDGE_CONTRACT_VERSION 1u

enum {
  RADISHLEX_INSTALLER_PHASE_READY = 1,
  RADISHLEX_INSTALLER_PHASE_AWAITING_USER_ACTION = 2,
  RADISHLEX_INSTALLER_PHASE_IN_PROGRESS = 3,
  RADISHLEX_INSTALLER_PHASE_COMPLETED = 4,
  RADISHLEX_INSTALLER_PHASE_RECOVERY_AVAILABLE = 5,
  RADISHLEX_INSTALLER_PHASE_BLOCKED = 6,
};

enum {
  RADISHLEX_INSTALLER_ACTION_NONE = 0,
  RADISHLEX_INSTALLER_ACTION_REFRESH = 1,
  RADISHLEX_INSTALLER_ACTION_BEGIN_FIRST_INSTALL = 2,
  RADISHLEX_INSTALLER_ACTION_BEGIN_UPGRADE = 3,
  RADISHLEX_INSTALLER_ACTION_BEGIN_REPAIR = 4,
  RADISHLEX_INSTALLER_ACTION_CONFIRM_QUIESCENCE = 5,
  RADISHLEX_INSTALLER_ACTION_RESUME_OPERATION = 6,
  RADISHLEX_INSTALLER_ACTION_RETRY_OPERATION = 7,
  RADISHLEX_INSTALLER_ACTION_REMOVE_PROGRAMS = 8,
  RADISHLEX_INSTALLER_ACTION_ABORT_PRE_SWITCH_UPGRADE = 9,
};

enum {
  RADISHLEX_INSTALLER_ERROR_NONE = 0,
  RADISHLEX_INSTALLER_ERROR_OPERATION_ACTIVE = 1,
  RADISHLEX_INSTALLER_ERROR_UNSAFE_DATA_ROOT = 2,
  RADISHLEX_INSTALLER_ERROR_UNSAFE_STATE_DIRECTORY = 3,
  RADISHLEX_INSTALLER_ERROR_INTERRUPTED_RECEIPT = 4,
  RADISHLEX_INSTALLER_ERROR_INVALID_RECEIPT = 5,
  RADISHLEX_INSTALLER_ERROR_UNEXPECTED_STATE_OBJECT = 6,
  RADISHLEX_INSTALLER_ERROR_ROOT_IDENTITY_CHANGED = 7,
  RADISHLEX_INSTALLER_ERROR_IO = 8,
  RADISHLEX_INSTALLER_ERROR_INSTALLED_RELEASE_IS_NEWER = 9,
  RADISHLEX_INSTALLER_ERROR_PRODUCT_IDENTITY_UNAVAILABLE = 10,
  RADISHLEX_INSTALLER_ERROR_MANUAL_RECOVERY_REQUIRED = 11,
  RADISHLEX_INSTALLER_ERROR_DRIVER_UNAVAILABLE = 12,
  RADISHLEX_INSTALLER_ERROR_UNKNOWN_DRIVER_RESULT = 13,
};

enum {
  RADISHLEX_INSTALLER_OPERATION_NONE = 0,
  RADISHLEX_INSTALLER_OPERATION_FIRST_INSTALL = 1,
  RADISHLEX_INSTALLER_OPERATION_UPGRADE = 2,
  RADISHLEX_INSTALLER_OPERATION_REPAIR = 3,
  RADISHLEX_INSTALLER_OPERATION_REMOVE_PROGRAMS = 4,
};

enum {
  RADISHLEX_INSTALLER_STATE_NONE = 0,
  RADISHLEX_INSTALLER_STATE_PREPARED = 1,
  RADISHLEX_INSTALLER_STATE_QUIESCED = 2,
  RADISHLEX_INSTALLER_STATE_TARGET_STAGED = 3,
  RADISHLEX_INSTALLER_STATE_SOURCE_PRESERVED = 4,
  RADISHLEX_INSTALLER_STATE_MANAGER_COMMITTED = 5,
  RADISHLEX_INSTALLER_STATE_PROGRAMS_COMMITTED = 6,
  RADISHLEX_INSTALLER_STATE_DATA_COORDINATING = 7,
  RADISHLEX_INSTALLER_STATE_DATA_SETTLED = 8,
  RADISHLEX_INSTALLER_STATE_FINAL_VERIFIED = 9,
  RADISHLEX_INSTALLER_STATE_COMPLETED = 10,
  RADISHLEX_INSTALLER_STATE_ABORTED_PRESERVED = 11,
  RADISHLEX_INSTALLER_STATE_ROLLBACK_REQUIRED = 12,
  RADISHLEX_INSTALLER_STATE_PROGRAMS_RESTORED = 13,
  RADISHLEX_INSTALLER_STATE_ROLLED_BACK = 14,
};

enum {
  RADISHLEX_INSTALLER_PROMPT_NONE = 0,
  RADISHLEX_INSTALLER_PROMPT_SELECT_NEUTRAL_AND_CLOSE_MANAGER = 1,
};

enum {
  RADISHLEX_INSTALLER_AUTH_EXPLICIT_CONFIRMATION = 1u << 0,
  RADISHLEX_INSTALLER_AUTH_DATA_RETENTION = 1u << 1,
  RADISHLEX_INSTALLER_AUTH_NEUTRAL_INPUT_SOURCE = 1u << 2,
  RADISHLEX_INSTALLER_AUTH_MANAGER_CLOSED = 1u << 3,
};

typedef struct RadishLexInstallerBridgeSnapshotV1 {
  uint32_t contract_version;
  uint32_t phase;
  uint32_t primary_action;
  uint32_t secondary_action;
  uint32_t stable_error;
  uint32_t operation_kind;
  uint32_t receipt_state;
  uint32_t progress_step;
  uint32_t manual_prompt;
} RadishLexInstallerBridgeSnapshotV1;

uint32_t radishlex_installer_bridge_contract_version(void);
RadishLexInstallerBridgeSnapshotV1 radishlex_installer_bridge_snapshot_v1(void);
RadishLexInstallerBridgeSnapshotV1
radishlex_installer_bridge_perform_v1(uint32_t action, uint32_t authorization_flags);

#endif
