#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import shutil
import socket
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from secrets import token_hex, token_urlsafe


REPO_ROOT = Path(__file__).resolve().parents[1]
COMPOSE_FILE = REPO_ROOT / "deploy" / "sync-server" / "docker-compose.yaml"
ENV_EXAMPLE = REPO_ROOT / "deploy" / "sync-server" / ".env.example"
DEFAULT_TIMEOUT_SECONDS = 60


class RehearsalError(RuntimeError):
    pass


def run_command(command: list[str], *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    try:
        return subprocess.run(
            command,
            cwd=REPO_ROOT,
            text=True,
            capture_output=capture,
            check=False,
        )
    except FileNotFoundError as exc:
        raise RehearsalError(f"{command[0]} is required for deployment rehearsal.") from exc


def run_required(command: list[str], *, capture: bool = False) -> subprocess.CompletedProcess[str]:
    result = run_command(command, capture=capture)
    if result.returncode != 0:
        if capture:
            sys.stdout.write(result.stdout)
            sys.stderr.write(result.stderr)
        raise RehearsalError(f"command failed with exit code {result.returncode}: {' '.join(command)}")
    return result


def choose_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind(("127.0.0.1", 0))
            return int(sock.getsockname()[1])
        except PermissionError:
            return 20000 + (int(token_hex(2), 16) % 20000)


def runtime_identity() -> tuple[int, int]:
    if not hasattr(os, "getuid") or not hasattr(os, "getgid"):
        raise RehearsalError("deployment rehearsal requires a Unix host identity.")
    uid = os.getuid()
    gid = os.getgid()
    if uid <= 0 or gid < 0:
        raise RehearsalError("deployment rehearsal refuses to run the sync container as root.")
    return uid, gid


def env_lines(project_name: str, data_path: Path, port: int, token: str, uid: int, gid: int) -> list[str]:
    return [
        f"COMPOSE_PROJECT_NAME={project_name}",
        "RADISHLEX_SYNC_IMAGE=radishlex-sync-server:dev",
        f"RADISHLEX_SYNC_RUNTIME_UID={uid}",
        f"RADISHLEX_SYNC_RUNTIME_GID={gid}",
        "RADISHLEX_SYNC_BIND=127.0.0.1",
        f"RADISHLEX_SYNC_PORT={port}",
        f"RADISHLEX_SYNC_PUBLIC_URL=http://127.0.0.1:{port}",
        f"RADISHLEX_SYNC_DATA_PATH={data_path}",
        "RADISHLEX_SYNC_LISTEN=0.0.0.0:7319",
        "RADISHLEX_SYNC_METADATA_PATH=/var/lib/radishlex/sync-server/sync-server.sqlite",
        "RADISHLEX_SYNC_BLOB_DIR=/var/lib/radishlex/sync-server/objects",
        "RADISHLEX_SYNC_MAX_OBJECT_BYTES=16777216",
        "RADISHLEX_SYNC_RECOVERY_READS_PER_HOUR=12",
        f"RADISHLEX_SYNC_ACCESS_TOKEN={token}",
    ]


def write_env(path: Path, project_name: str, data_path: Path, port: int, token: str, uid: int, gid: int) -> None:
    path.write_text(
        "# Generated by check-sync-server-deployment-rehearsal.py; do not commit.\n"
        + "\n".join(env_lines(project_name, data_path, port, token, uid, gid))
        + "\n",
        encoding="utf-8",
    )
    path.chmod(0o600)


def prepare_data_dir(path: Path) -> None:
    sync_dir = path / "sync-server"
    objects_dir = sync_dir / "objects"
    objects_dir.mkdir(parents=True, exist_ok=True)
    for directory in (path, sync_dir, objects_dir):
        directory.chmod(0o700)


def assert_mode(path: Path, expected: int, label: str) -> None:
    if path.is_symlink():
        raise RehearsalError(f"{label} must not be a symlink.")
    actual = path.stat().st_mode & 0o777
    if actual != expected:
        raise RehearsalError(f"{label} mode is {actual:o}, expected {expected:o}.")


def assert_compose_source_hardened() -> None:
    compose = COMPOSE_FILE.read_text(encoding="utf-8")
    required = [
        'user: "${RADISHLEX_SYNC_RUNTIME_UID:-10001}:${RADISHLEX_SYNC_RUNTIME_GID:-10001}"',
        "read_only: true",
        "cap_drop:\n      - ALL",
        "- no-new-privileges:true",
        '"${RADISHLEX_SYNC_BIND:-127.0.0.1}:${RADISHLEX_SYNC_PORT:-7319}:7319"',
    ]
    for contract in required:
        if contract not in compose:
            raise RehearsalError(f"deployment compose is missing hardening contract: {contract!r}")


def compose_command(env_path: Path, *args: str) -> list[str]:
    return [
        "docker",
        "compose",
        "-f",
        str(COMPOSE_FILE),
        "--env-file",
        str(env_path),
        *args,
    ]


def request_status(url: str, token: str | None = None, timeout: float = 3.0) -> tuple[int, str]:
    request = urllib.request.Request(url)
    if token is not None:
        request.add_header("Authorization", f"Bearer {token}")
    try:
        with urllib.request.urlopen(request, timeout=timeout) as response:
            body = response.read().decode("utf-8", errors="replace")
            return int(response.status), body
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        return int(exc.code), body
    except OSError as exc:
        raise RehearsalError(f"failed to reach sync server at {url}: {exc}") from exc


def wait_for_auth_gate(base_url: str, token: str, timeout_seconds: int) -> None:
    deadline = time.monotonic() + timeout_seconds
    last_error: Exception | None = None
    while time.monotonic() < deadline:
        try:
            status, body = request_status(f"{base_url}/api/v1/domains/rehearsal-auth/state")
            if status == 401 and "unauthenticated" in body:
                authorized_status, authorized_body = request_status(
                    f"{base_url}/api/v1/domains/rehearsal-auth/state",
                    token=token,
                )
                if authorized_status == 404 and "not_found" in authorized_body:
                    return
                last_error = RehearsalError(
                    f"authorized request returned {authorized_status}: {authorized_body[:200]}"
                )
            else:
                last_error = RehearsalError(f"unauthorized request returned {status}: {body[:200]}")
        except Exception as exc:  # noqa: BLE001
            last_error = exc
        time.sleep(1)
    raise RehearsalError(f"sync server auth gate did not become ready: {last_error}")


def assert_data_layout(data_path: Path) -> None:
    metadata = data_path / "sync-server" / "sync-server.sqlite"
    objects = data_path / "sync-server" / "objects"
    if not metadata.is_file():
        raise RehearsalError(f"metadata database was not created: {metadata}")
    if not objects.is_dir():
        raise RehearsalError(f"object directory was not created: {objects}")
    assert_mode(data_path, 0o700, "deployment data root")
    assert_mode(data_path / "sync-server", 0o700, "sync-server data directory")
    assert_mode(objects, 0o700, "encrypted object directory")
    assert_mode(metadata, 0o600, "SQLite metadata")


def assert_backup_safe(backup_path: Path, token: str) -> None:
    assert_data_layout(backup_path)
    for path in backup_path.rglob("*"):
        if path.name.endswith(".env"):
            raise RehearsalError("cold backup unexpectedly contains an env file.")
        if path.is_file() and token.encode("utf-8") in path.read_bytes():
            raise RehearsalError("cold backup unexpectedly contains the bearer token.")


def assert_logs_redacted(env_path: Path, token: str) -> None:
    result = run_required(compose_command(env_path, "logs", "--no-color", "--tail=200", "sync-server"), capture=True)
    logs = result.stdout + result.stderr
    forbidden = [
        token,
        "Authorization:",
        "Bearer ",
        "encrypted_payload",
        "signature bytes",
        "wrapped material",
        "recovery material",
    ]
    for phrase in forbidden:
        if phrase and phrase in logs:
            raise RehearsalError(f"sync-server logs contain forbidden sensitive marker: {phrase!r}")


def redacted_text(text: str, token: str) -> str:
    return text.replace(token, "<redacted-access-token>")


def print_compose_diagnostics(env_path: Path, token: str) -> None:
    for args in (("ps",), ("logs", "--no-color", "--tail=120", "sync-server")):
        result = run_command(compose_command(env_path, *args), capture=True)
        output = redacted_text(result.stdout + result.stderr, token).strip()
        if output:
            print(f"--- docker compose {' '.join(args)} ---")
            print(output)


def down(env_path: Path) -> None:
    result = run_command(compose_command(env_path, "down"))
    if result.returncode != 0:
        raise RehearsalError(f"failed to stop compose project for {env_path}")


def print_redacted_config(result: subprocess.CompletedProcess[str], token: str) -> None:
    output = (result.stdout + result.stderr).replace(token, "<redacted-access-token>")
    if output.strip():
        print(output.rstrip())


def run_rehearsal(args: argparse.Namespace) -> int:
    if not COMPOSE_FILE.is_file():
        raise RehearsalError(f"missing compose file: {COMPOSE_FILE}")
    if not ENV_EXAMPLE.is_file():
        raise RehearsalError(f"missing env example: {ENV_EXAMPLE}")

    suffix = token_hex(4)
    token = token_urlsafe(48)
    uid, gid = runtime_identity()
    port = args.port if args.port is not None else choose_port()
    project_name = f"radishlex-sync-rehearsal-{suffix}"
    temp_root = Path(tempfile.mkdtemp(prefix="radishlex-sync-rehearsal."))
    temp_root.chmod(0o700)
    data_path = temp_root / "data"
    backup_path = temp_root / "backup"
    restore_data_path = temp_root / "restore-data"
    env_path = temp_root / "radishlex-sync.env"
    restore_env_path = temp_root / "radishlex-sync-restore.env"
    base_url = f"http://127.0.0.1:{port}"
    started_envs: list[Path] = []

    assert_compose_source_hardened()
    prepare_data_dir(data_path)
    write_env(env_path, project_name, data_path, port, token, uid, gid)
    assert_mode(temp_root, 0o700, "rehearsal temp root")
    assert_mode(env_path, 0o600, "rehearsal env")
    print(f"Rehearsal temp root: {temp_root}")
    print(f"Rehearsal port: {port}")
    print("Generated bearer token: <redacted>")

    try:
        config_result = run_required(compose_command(env_path, "config"), capture=True)
        if args.print_config:
            print_redacted_config(config_result, token)
        if args.config_only:
            print("Compose config rehearsal passed.")
            return 0

        run_required(compose_command(env_path, "up", "--build", "-d"))
        started_envs.append(env_path)
        wait_for_auth_gate(base_url, token, args.timeout_seconds)
        assert_data_layout(data_path)
        assert_logs_redacted(env_path, token)
        down(env_path)
        started_envs.remove(env_path)

        shutil.copytree(data_path, backup_path)
        assert_backup_safe(backup_path, token)
        shutil.copytree(backup_path, restore_data_path)
        prepare_data_dir(restore_data_path)
        write_env(restore_env_path, f"{project_name}-restore", restore_data_path, port, token, uid, gid)
        assert_mode(restore_env_path, 0o600, "restore rehearsal env")
        restore_config_result = run_required(compose_command(restore_env_path, "config"), capture=True)
        if args.print_config:
            print_redacted_config(restore_config_result, token)
        run_required(compose_command(restore_env_path, "up", "--build", "-d"))
        started_envs.append(restore_env_path)
        wait_for_auth_gate(base_url, token, args.timeout_seconds)
        assert_data_layout(restore_data_path)
        assert_logs_redacted(restore_env_path, token)
        down(restore_env_path)
        started_envs.remove(restore_env_path)

        print("Sync server deployment rehearsal passed.")
        return 0
    except RehearsalError:
        for path in started_envs:
            if path.exists():
                print_compose_diagnostics(path, token)
        raise
    finally:
        for path in list(started_envs):
            if path.exists():
                try:
                    down(path)
                except RehearsalError:
                    pass
        if args.keep_artifacts:
            print(f"Kept rehearsal artifacts under: {temp_root}")
        else:
            shutil.rmtree(temp_root, ignore_errors=True)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run a short-lived sync server deployment rehearsal with temp env, token, data, backup, and restore."
    )
    parser.add_argument("--config-only", action="store_true", help="Only validate compose config with generated temp env.")
    parser.add_argument("--keep-artifacts", action="store_true", help="Keep the temp env and data directories for inspection.")
    parser.add_argument("--print-config", action="store_true", help="Print redacted docker compose config output.")
    parser.add_argument("--port", type=int, help="Host port to use. Default: choose an available local port.")
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=DEFAULT_TIMEOUT_SECONDS,
        help=f"Seconds to wait for sync server readiness. Default: {DEFAULT_TIMEOUT_SECONDS}.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        return run_rehearsal(args)
    except RehearsalError as exc:
        print(f"deployment rehearsal failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
